image: docker:latest


build_job:
  stage: build
  script:
    - ls
    - echo "starting job..."
    - echo $PATH
    - cargo build
    - echo job finished
  only:
    - feature/ci
    - feature/socketcan
    - main
