[package]
name = "rasteroids"
version = "0.1.0"
authors = ["brandon phelps"]
edition = "2018"

[features]
default = []

[dependencies]

[dependencies.sdl2]
version="0.35"
default-features = false
features = ["ttf", "image", "bundled"]
optional = false

