[package]
name = "rasteroids"
version = "0.1.0"
authors = ["brandon phelps"]
edition = "2018"

[features]
default = ["gui"]
gui = []

[dependencies]
rand="0.7.3"

[dependencies.sdl2]
version="0.35"
default-features = false
features = ["ttf", "image", "bundled"]
optional = false

