[package]
name = "rminions"
version = "0.1.0"
authors = ["brandon phelps <bwp44f@mst.edu>"]
edition = "2018"


[features]
default = []
# gui = ["sdl2"]


[dependencies]
rand="0.7.3"

[dependencies.sdl2]
version="0.34"
default-features = false
features = ["ttf", "image"]
optional = false